[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ivbox"
version = "0.2.0"
description = "Better structure and provides utils functions both general and ui-flet"
readme = "README.md"
authors = [
    { name = "Ivan Gonzalez", email = "ivanartista96@example.com" }
]
requires-python = ">=3.10"

dependencies = [
    "polars",
    "pandas",
    "numpy",
    "requests",
    "flet"
]

[tool.setuptools.packages.find]
where = ["."]