traducciones={
    "jerseyNumber": "Número camiseta",
    "totalPass": "Pases totales",
    "accuratePass": "Pases acertados",
    "totalLongBalls": "Balones largos totales",
    "accurateLongBalls": "Balones largos acertados",
    "goalAssist": "Asistencias",
    "accurateOwnHalfPasses": "Pases acertados en propio campo",
    "totalOwnHalfPasses": "Pases totales en propio campo",
    "totalOppositionHalfPasses": "Pases totales en campo rival",
    "duelLost": "Duelos perdidos",
    "totalContest": "Duelos totales",
    "ballRecovery": "Balones recuperados",
    "errorLeadToAGoal": "Error que acabó en gol",
    "penaltyConceded": "Penaltis cometidos",
    "fouls": "Faltas cometidas",
    "minutesPlayed": "Minutos jugados",
    "touches": "Toques",
    "rating": "Valoración",
    "possessionLostCtrl": "Pérdidas de posesión",
    "expectedAssists": "Asistencias esperadas (xA)",
    "goalsPrevented": "Goles evitados",
    "passValueNormalized": "Valor pase (normalizado)",
    "dribbleValueNormalized": "Valor regate (normalizado)",
    "defensiveValueNormalized": "Valor defensivo (normalizado)",
    "accurateOppositionHalfPasses": "Pases acertados en campo rival",
    "totalCross": "Centros totales",
    "aerialWon": "Duelos aéreos ganados",
    "duelWon": "Duelos ganados",
    "dispossessed": "Balones perdidos",
    "totalClearance": "Despejes totales",
    "interceptionWon": "Intercepciones",
    "totalTackle": "Entradas totales",
    "wonTackle": "Entradas ganadas",
    "wasFouled": "Faltas recibidas",
    "errorLeadToAShot": "Error que acabó en tiro",
    "totalOffside": "Fuera de juego",
    "aerialLost": "Duelos aéreos perdidos",
    "shotOffTarget": "Tiros fuera",
    "unsuccessfulTouch": "Controles fallidos",
    "expectedGoals": "Goles esperados (xG)",
    "shotValueNormalized": "Valor tiro (normalizado)",
    "challengeLost": "Retos perdidos",
    "accurateCross": "Centros acertados",
    "wonContest": "Duelos ganados",
    "onTargetScoringAttempt": "Tiros a puerta",
    "goals": "Goles",
    "clearanceOffLine": "Balón sacado bajo palos",
    "outfielderBlock": "Bloqueos",
    "expectedGoalsOnTarget": "xG en tiros a puerta",
    "bigChanceCreated": "Ocasiones claras creadas",
    "keyPass": "Pases clave",
    "blockedScoringAttempt": "Tiros bloqueados",
    "savedShotsFromInsideTheBox": "Paradas dentro del área",
    "penaltyFaced": "Penaltis enfrentados",
    "saves": "Paradas",
    "keeperSaveValue": "Valor paradas",
    "goalkeeperValueNormalized": "Valor portero (normalizado)",
    "totalKeeperSweeper": "Salidas del portero",
    "accurateKeeperSweeper": "Salidas acertadas del portero",
    "bigChanceMissed": "Ocasiones claras falladas",
    "penaltyWon": "Penaltis ganados",
    "captain": "Capitán",
    "penaltySave": "Penaltis parados",
    "penaltyMiss": "Penaltis fallados",
    "goodHighClaim": "Balones altos atrapados",
    "punches": "Puños",
    "hitWoodwork": "Balón al palo",
    "lastManTackle": "Entrada como último hombre",
    "ownGoals": "Autogoles",
    "crossNotClaimed": "Centros no atrapados",
    "userCount": "Popularidad",
    "shirtNumber": "Número camiseta",
    "totalShots": "Tiros totales",
    "position": "Posición",
    "substitute": "Suplente"
}

stats = [
    "jerseyNumber",
    "totalPass",
    "accuratePass",
    "totalLongBalls",
    "accurateLongBalls",
    "goalAssist",
    "accurateOwnHalfPasses",
    "totalOwnHalfPasses",
    "totalOppositionHalfPasses",
    "duelLost",
    "totalContest",
    "ballRecovery",
    "errorLeadToAGoal",
    "penaltyConceded",
    "fouls",
    "minutesPlayed",
    "touches",
    "rating",
    "possessionLostCtrl",
    "expectedAssists",
    "goalsPrevented",
    "passValueNormalized",
    "dribbleValueNormalized",
    "defensiveValueNormalized",
    "accurateOppositionHalfPasses",
    "totalCross",
    "aerialWon",
    "duelWon",
    "dispossessed",
    "totalClearance",
    "interceptionWon",
    "totalTackle",
    "wonTackle",
    "wasFouled",
    "errorLeadToAShot",
    "totalOffside",
    "aerialLost",
    "shotOffTarget",
    "unsuccessfulTouch",
    "expectedGoals",
    "shotValueNormalized",
    "challengeLost",
    "accurateCross",
    "wonContest",
    "onTargetScoringAttempt",
    "goals",
    "clearanceOffLine",
    "outfielderBlock",
    "expectedGoalsOnTarget",
    "bigChanceCreated",
    "keyPass",
    "blockedScoringAttempt",
    "savedShotsFromInsideTheBox",
    "penaltyFaced",
    "saves",
    "keeperSaveValue",
    "goalkeeperValueNormalized",
    "totalKeeperSweeper",
    "accurateKeeperSweeper",
    "bigChanceMissed",
    "penaltyWon",
    "captain",
    "penaltySave",
    "penaltyMiss",
    "goodHighClaim",
    "punches",
    "hitWoodwork",
    "lastManTackle",
    "ownGoals",
    "crossNotClaimed",
    "userCount",
    "shirtNumber",
    "totalShots",
    "position",
    "substitute"
]